### ISSUE TITLE
Little Question on OTP

### ISSUE THREAD

**Issue by teemop09** [jyyyyylim/fastAttendix#1]
Do you know around how many times can you enter wrong OTP number before the system limits you? 

Thanks.

**Comment by jyyyyylim** [comment]
hi, to my knowledge the server behaves very inconsistently on this part
i think the closest thing to this is how fast you repeatedly attempt otp input, as the server only seems to care about ratelimits 

i dont have anything else clear as classes ended months ago, do update me on its behavior if you do use it
im sure they mightve changed something since their total system denial a month ago

**Comment by teemop09** [comment]
Alright thanks for the info, will get back to you *IF* I continue to look into it.
